
CREATE DATABASE IF NOT EXISTS loginsystem;
USE loginsystem;


CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phonenumber VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE USER IF NOT EXISTS 'jamlick'@'127.0.0.1' IDENTIFIED BY '30690770';


GRANT ALL PRIVILEGES ON loginsystem.* TO 'jamlick'@'127.0.0.1';
FLUSH PRIVILEGES;

EXIT;
